import { getItems } from '@/app/utils'
import Layout from '@/components/layout/Layout'
import Button from '@mui/material/Button'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

type Props = {
  blogPosts: any
}

export default function UsefulInformation({ blogPosts }: Props) {
  const renderPosts = blogPosts.data.map((post: any) => {
    const image = post?.attributes?.images?.data?.[0]?.attributes?.formats
    const imageSrc = `${process.env.NEXT_PUBLIC_API_URL}${image?.medium.url}`

    return (
      <Stack key={post.id} pt={4} direction={{ xs: 'column', md: 'row' }} spacing={2}>
        <Stack sx={{ position: 'relative', minWidth: { xs: '100%', md: 300 }, height: { xs: 300, md: 300 } }}>
          <Image priority alt={post?.attributes?.images?.data?.[0]?.attributes?.alternativeText ?? ''}
            layout='fill' objectFit='cover' src={imageSrc} />
        </Stack>
        <Stack>
          <Link passHref href={'/naudinga-zinoti/' + post.attributes.slug}>
            <Typography variant='h6'>
              {post.attributes.title}
            </Typography>
          </Link>
          <Typography>
            {post.attributes.shortContent}
          </Typography>
          <Stack pt={2}>
            <Link passHref href={'/naudinga-zinoti/' + post.attributes.slug}>
              <Button variant='contained' >
                Skaityti straipsnį
              </Button>
            </Link>
          </Stack>
        </Stack>
      </Stack>
    )
  })
  return (
    <>
      <Head>
        <title>{"Naudinga žinoti"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Stack sx={{ px: { xl: 2, md: 4, xs: 2 }, pt: { xl: 2, md: 4, xs: 2 }, pb: 8 }}>
          <Typography variant='h4' fontWeight={600}>
            NAUDINGA ŽINOTI
          </Typography>
          <Stack>
            {renderPosts}
          </Stack>
        </Stack>
      </Layout>
    </>
  )
}
export const getServerSideProps: GetServerSideProps = async () => {
  const blogPosts = await getItems('blog-posts', 'populate=deep') ?? null

  return {
    props: {
      blogPosts: blogPosts ?? null
    }
  }
}
