import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getItems } from '@/app/utils'
import { GetServerSideProps } from 'next'
import { VehiclesType } from '@/app/VehiclesType'

const inter = Inter({ subsets: ['latin'] })

type Props = {
  vehicles: VehiclesType[];
}
export default function Home({ vehicles }: Props) {
  return (
    <>
      <Head>
        <title>{"Vehicle"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        {JSON.stringify(vehicles)}
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const vehicles = await getItems('vehicles')

  return {
    props: {
      vehicles: vehicles,
    }
  }
}
