import ContactForm from '@/components/ContactForm'
import Layout from '@/components/layout/Layout'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import Head from 'next/head'


export default function Contacts() {
  return (
    <>
      <Head>
        <title>{"Contacts"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Typography variant='h4' fontWeight={600}>
          Kontaktai
        </Typography>
        <Stack pt={2}>
          <ContactForm />
        </Stack>
      </Layout>
    </>
  )
}
