import { VehiclesType } from '@/app/VehiclesType'
import { getItems } from '@/app/utils'
import { GetServerSideProps } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

type Props = {
    vehicles?: VehiclesType;
}
export default function Vehicles({ vehicles }: Props) {
    const renderVehicles = vehicles?.data?.map((vehicle) => {
        return (
            <div key={vehicle.id}>
                <Link href={'/vehicles/' + vehicle?.attributes?.slug} passHref>
                    {vehicle.attributes?.make},
                    {vehicle.attributes?.model},
                    {vehicle.attributes?.firstRegDate},
                    {vehicle.attributes?.engineCapacityCC}
                </Link>
            </div>
        )
    })
    return (
        <>
            <Head>
                <title>{"Vehicles"}</title>
                <meta name="description" content={"Generated by create next app"} />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${inter.className}`}>
                {renderVehicles}
            </main>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const vehicles = await getItems('vehicles')

    return {
        props: {
            vehicles: vehicles,
        }
    }
}
