import { VehiclesType } from '@/app/VehiclesType'
import { getItems } from '@/app/utils'
import Layout from '@/components/layout/Layout'
import { Typography } from '@mui/material'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

type Props = {
    vehicles?: VehiclesType;
}
export default function Vehicles({ vehicles }: Props) {
    const renderVehicles = vehicles?.data?.map((vehicle) => {
        return (
            <Typography key={vehicle.id}>
                <Link href={'/vehicles/' + vehicle?.attributes?.slug} passHref>
                    {vehicle.attributes?.make},
                    {vehicle.attributes?.model},
                    {vehicle.attributes?.firstRegDate},
                    {vehicle.attributes?.engineCapacityCC}
                </Link>
            </Typography>
        )
    })
    return (
        <>
            <Head>
                <title>{"Vehicles"}</title>
                <meta name="description" content={"Generated by create next app"} />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                {renderVehicles}
            </Layout>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const vehicles = await getItems('vehicles')

    return {
        props: {
            vehicles: vehicles,
        }
    }
}
