import { VehiclesType } from '@/app/types/VehiclesType'
import { getItems } from '@/app/utils'
import Layout from '@/components/layout/Layout'
import VehicleCard from '@/components/vehicles/VehicleCard'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

type Props = {
    vehicles?: VehiclesType;
}
export default function Vehicles({ vehicles }: Props) {
    const renderVehicles = vehicles?.data?.map((vehicle) => {
        return (
            <VehicleCard key={vehicle.id} vehicle={vehicle} />
        )
    })
    return (
        <>
            <Head>
                <title>{"Vehicles"}</title>
                <meta name="description" content={"Generated by create next app"} />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Typography variant='h4' fontWeight={600}>
                    VEHICLES
                </Typography>
                {renderVehicles}
            </Layout>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const vehicles = await getItems('vehicles')

    return {
        props: {
            vehicles: vehicles,
        }
    }
}
