import { ObjectsType } from '@/app/types/ObjectsType'
import { getItems } from '@/app/utils'
import Layout from '@/components/layout/Layout'
import ObjectCard from '@/components/objects/ObjectCard'
import { Grid, Stack } from '@mui/material'
import Typography from '@mui/material/Typography'
import { GetServerSideProps } from 'next'
import Head from 'next/head'

type Props = {
    objects?: ObjectsType | null;
}
export default function Objects({ objects }: Props) {
    const renderObjects = objects?.data?.map((object) => {
        return (
            <Grid key={object.id} item xs={12} sm={6} lg={3}>
                <ObjectCard object={object} />
            </Grid>
        )
    })
    return (
        <>
            <Head>
                <title>{"Objects"}</title>
                <meta name="description" content={"Generated by create next app"} />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Stack pb={4}>
                    <Typography variant='h4' fontWeight={600}>
                        OBJECTS
                    </Typography>
                </Stack>
                <Grid container direction={'row'} spacing={4} sx={{}}>
                    {renderObjects}
                    {renderObjects}
                    {renderObjects}
                    {renderObjects}
                    {renderObjects}
                    {renderObjects}
                    {renderObjects}
                </Grid>
            </Layout>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const objects = await getItems('objects') ?? null
    console.log(objects, "objects");

    return {
        props: {
            objects: objects ?? null,
        }
    }
}
