import { VehicleType } from '@/app/VehiclesType'
import { getItem, getItemBySlug } from '@/app/utils'
import { GetServerSideProps } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

type Props = {
  vehicle?: VehicleType;
}
export default function Home({ vehicle }: Props) {
  return (
    <>
      <Head>
        <title>{"Vehicle"}</title>
        <meta name="description" content={"Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div key={vehicle?.id}>
          {vehicle?.attributes?.make},
          {vehicle?.attributes?.model},
          {vehicle?.attributes?.firstRegDate},
          {vehicle?.attributes?.engineCapacityCC}
        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context: any) => {
  const { slug } = context.params

  const vehicle = await getItemBySlug('vehicles', slug)

  return {
    props: {
      vehicle: vehicle?.data?.[0] ?? null,
    }
  }
}
