import { VehicleType } from '@/app/VehiclesType'
import { getItemBySlug } from '@/app/utils'
import Layout from '@/components/layout/Layout'
import { Typography } from '@mui/material'
import { GetServerSideProps } from 'next'
import Head from 'next/head'

type Props = {
  vehicle?: VehicleType;
}
export default function Home({ vehicle }: Props) {
  return (
    <>
      <Head>
        <title>{"Vehicle"}</title>
        <meta name="description" content={"Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Typography variant='h4' fontWeight={600}>
          VEHICLE
        </Typography>
        <Typography key={vehicle?.id}>
          {vehicle?.attributes?.make},
          {vehicle?.attributes?.model},
          {vehicle?.attributes?.firstRegDate},
          {vehicle?.attributes?.engineCapacityCC}
        </Typography>
      </Layout>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context: any) => {
  const { slug } = context.params

  const vehicle = await getItemBySlug('vehicles', slug)

  return {
    props: {
      vehicle: vehicle?.data?.[0] ?? null,
    }
  }
}
